<a href="https://colab.research.google.com/github/shanmughamkarthik-eng/numpy/blob/main/basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
# 1. CREATING ARRAYS

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
#Addition

plus_one = arr + 1
print(plus_one)

[2 3 4 5 6]


In [6]:
plus_ten = arr + 10
print(plus_ten)

[11 12 13 14 15]


In [7]:
#Multiplication

multiply_seven = arr * 7
print(multiply_seven)


[ 7 14 21 28 35]
